### GET HELLO
GET localhost:8080/hello
Content-Type: application/json

### GET HEALTH
GET localhost:8080/health
Content-Type: application/json

### POST NOTA 1
POST localhost:8080/v1/nota
Content-Type: application/json

{
  "titulo" : "ttt",
  "cuerpo" : "ccc",
  "fecha" : "ddd"
}

### POST NOTA 2
POST localhost:8080/v1/nota
Content-Type: application/json

{
"titulo" : "t2",
"cuerpo" : "c2",
"fecha" : "d2"
}

### GET NOTA Sort=id
GET localhost:8080/v1/nota?sort=id
Content-Type: application/json

### GET NOTA Sort=id
GET localhost:8080/v1/nota?sort=titulo
Content-Type: application/json

### GET NOTA Sort=cuerpo
GET localhost:8080/v1/nota?sort=cuerpo
Content-Type: application/json
